name: DaLI-DM
channels: 
  - conda-forge
dependencies:
  - python == 3.8.8
  - pip == 21.0.1
  - numpy == 1.20.1
  - pandas == 1.2.4
  - matplotlib == 3.3.4
  - sklearn == 0.24.1
  - seaborn == 0.11.1
  - Ipython == 7.22.0
  - ipywidgets == 7.6.3
  - mlxtend
  - pip:
    - efficient-apriori